version: '2'
services:
  web:
    build: .
    ports:
      - "8090:80"
    volumes:
      - ~/Scrivania/my-docker/glocalnow-docker/glocalnow:/var/www/html
    external_links:
      - docker-mysql:db
    network_mode: bridge
    #depends_on:
    #  - db
    #links:
    #  - db
